### ISSUE TITLE
FPM Socket Issue in Nginx Config when Cloning Virtual Server

### ISSUE THREAD

**Issue by bobbyschultz** [virtualmin/virtualmin-nginx#57] opened 2023-06-23 04:26 UTC
Webmin version 	2.021
Usermin version 	1.861
Virtualmin version 	7.7
Nginx version:          1.18.0
PHP version:             8.1

During the Clone Virtual Server process, the following error is thrown after "Applying Nginx Configuration": `configuration is invalid : nginx: [emerg] no path in the unix domain socket in upstream "unix:" in /etc/nginx/sites-enabled/xxxx.conf:33 nginx: configuration file /etc/nginx/nginx.conf test failed`

Restarting Nginx manually results in a failure to start. Setting the PHP mode to FPM on the cloned virtual server fixes the issue.

It looks like this happens when a virtual server with the PHP mode set to FPM is cloned. The new virtual server's PHP mode is set to FCGId by default. The resulting virtual server's Nginx config is missing the reference to the FPM socket file in the "fastcgi_pass" directive. The socket file is created in /var/php-fpm/ but the reference is missing in the Nginx config.

Once the virtual server is put into FPM mode for the first time the "fastcgi_pass" directive is fixed, but until then, Nginx will fail to start.
![Capture](https://github.com/virtualmin/virtualmin-nginx/assets/8755606/3cec7fd9-69c5-4b7a-bc7b-e7aa71631280)
![PHP Options](https://github.com/virtualmin/virtualmin-nginx/assets/8755606/d4197a12-105f-42dc-b982-de90b9e28c2a)
![Virtualhost Config](https://github.com/virtualmin/virtualmin-nginx/assets/8755606/b98265f2-18ef-4409-a2e9-2bcdcab8c2ff)
![V Host Config Corrected](https://github.com/virtualmin/virtualmin-nginx/assets/8755606/f2a5b07d-6b3c-45ba-a90b-997a73a23203)

**Comment by jcameron** [comment] 2023-06-23 05:19
Ok I see the cause of this - it will be fixed in the next Nginx module release.

**Closed by jcameron** 2023-06-23 05:19 UTC
